# Generated by Django 5.0.6 on 2024-06-17 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoAntropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura (m)')),
                ('circunferencia_cintura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Circunferência da Cintura (cm)')),
                ('circunferencia_quadril', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Circunferência do Quadril (cm)')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Masculino', max_length=20)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('ocupacao', models.CharField(blank=True, max_length=150)),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('celular', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d{3}-\\d{5}')], verbose_name='Celular')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricionista', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
