# Generated by Django 4.2.13 on 2024-06-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_medicao',
            field=models.DateField(null=0, verbose_name='Data da Medição'),
        ),
    ]
