# Generated by Django 4.2.13 on 2024-06-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0002_alter_paciente_data_medicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_medicao',
            field=models.DateField(null=True, verbose_name='Data da Medição'),
        ),
    ]
