# Generated by Django 5.0.6 on 2024-06-18 02:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0002_rename_user_id_medicaoantropometrica_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nutricionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_nutricionista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MedidaAntropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medicao', models.DateField(verbose_name='Data da Medição')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (cm)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('circunferencia_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunferência Abdominal (cm)')),
                ('circunferencia_quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunferência do Quadril (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Índice de Massa Corporal (IMC)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='nutriApp.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicaoAntropometrica',
        ),
    ]
