# Generated by Django 4.2.13 on 2024-06-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0003_alter_paciente_data_medicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historico',
            field=models.TextField(blank=True, verbose_name='Histórico'),
        ),
    ]
