# Generated by Django 4.2.13 on 2024-06-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0003_alter_paciente_celular_alter_paciente_cep_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedidaAntropometrica',
            new_name='Medidas',
        ),
    ]
