# Generated by Django 5.0.6 on 2024-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0006_alter_paciente_alergias_alter_paciente_historico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_alimentar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Histórico Alimentar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='objetivo_consulta',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Objetivo da Consulta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='preferencias_e_restricoes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Preferências e Restrições'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rotina_de_alimentacao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Rotina de Alimentação'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rotina_de_atividade_fisica',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Rotina de Atividade Física'),
        ),
    ]
