# Generated by Django 5.0.6 on 2024-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0007_alter_paciente_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Outro', max_length=20),
        ),
    ]
